import '../models/menu_model.dart';

final bookIndex = [
  Section(
    "DOOM:UAC手册",
    "金钱、技术、荣耀与贡献精神是人们谈及DOOM时经常使用的词汇。它是一个纯粹而直爽的存在，但那简洁明了的游戏设计理念背后，所承载着一个个精彩纷呈的故事又使其成为了独特的文化标杆。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "免责声明",
        "非商业性使用-相同方式共享 4.0 协议(CC BY-NC-SA 4.0)",
        total: 3,
        section: 0,
        chapter: 1,
      ),
      Chapter(
        "序",
        "你只需要冰箱里拥有足够的披萨和无糖可乐和一台廉价的个人电脑，以及为之献身的决心。我们睡过地板，我们砥砺前行。”——约翰.卡马克/《DOOM启示录》/第16章引述",
        total: 3,
        section: 0,
        chapter: 2,
      ),
      Chapter(
        "目录",
        "8章",
        total: 3,
        section: 0,
        chapter: 3,
      ),
    ],
  ),
  Section(
    "第一章：DOOM创世纪[上]",
    "作为游戏产业最初的一批开发者，他们在当时完全不具备开发条件的环境下，用自己的智慧和对工具的巧妙运用，实现了如今看似不可能的任务。这些为后世的游戏发展启迪做出贡献的先驱，不应当就此被人们所遗忘。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "1.1 启蒙时代",
        "任何事物在它羽翼丰满之前，总会经历一段鲜为人知，不断碰壁却充满迸发灵感的时期。",
        total: 6,
        section: 1,
        chapter: 1,
      ),
      Chapter(
        "1.2 约翰",
        "每个时代都需要一个关于专注者如何造就奇迹的故事。",
        total: 6,
        section: 1,
        chapter: 2,
      ),
      Chapter(
        "1.3（另一个）约翰",
        "约翰.罗梅罗",
        total: 6,
        section: 1,
        chapter: 3,
      ),
      Chapter(
        "1.4 寄人篱下的日子",
        "这就是那个时不时给我们寄游戏来的家伙？",
        total: 6,
        section: 1,
        chapter: 4,
      ),
      Chapter(
        "1.5 焕发“本我”",
        "“无论他们如何担忧，最终都会被实际游戏成品所征服的。”",
        total: 3,
        section: 1,
        chapter: 5,
      ),
      Chapter(
        "1.6 DooM降临",
        "“仅此一次，我们团结一心去挑战自我，合力创造出一款当时我们所能想象到的最好的游戏。“",
        total: 6,
        section: 1,
        chapter: 6,
      ),
    ],
  ),
  Section(
    "第二章：DOOM创世纪[下]",
    "它是西方年轻人一夜暴富的典型案例，是第一人称射击类型的启蒙老师，是技术先驱与暴力题材的奠基者等等。诸多荣耀与非议笼罩在这个游戏身上，却反而让它逐渐在大众眼中变得朦胧而遥远。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "2.1 地下世界”的王者",
        "“我们把游戏免费提供给你们，把它当成自己的东西去卖，赚到的钱都归你们自己。”",
        total: 5,
        section: 2,
        chapter: 1,
      ),
      Chapter(
        "2.2 史上最快的地牢爬行",
        "“这是一种运用无声语言进行引导的工作，有着比文字更多的可能性。”",
        total: 5,
        section: 2,
        chapter: 2,
      ),
      Chapter(
        "2.3 看到没有？这叫做互联网",
        "花那么多钱构建网络可不是来让年轻人互相发射火箭炮的。",
        total: 5,
        section: 2,
        chapter: 3,
      ),
      Chapter(
        "2.4 你无法毁灭DOOM",
        "“摇滚精神其实很简单，那就是与任何试图谋杀自由的家伙抗争到底。”",
        total: 5,
        section: 2,
        chapter: 4,
      ),
      Chapter(
        "万物皆DOOM，DOOM归众生",
        "“DOOM很容易就能玩到...，发布源代码是我们做过最好的事情。”",
        total: 5,
        section: 2,
        chapter: 5,
      ),
    ],
  ),
  Section(
    "第三章：DOOM4的消逝与新生",
    "约翰.卡马克有了改造到巅峰状态的法拉利跑车，有了最好的开发工具和环境，...却不会再有一个留着长发、能陪他在浸水小屋里熬夜写代码的罗梅罗了。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "3.1 在做了",
        "虽然难免会感到有那么一丝惆怅与遗憾，人们也不应当因为昨日美好的景色而停止前进。",
        total: 4,
        section: 3,
        chapter: 1,
      ),
      Chapter(
        "3.2 深陷泥潭",
        "《毁灭战士4》没有灵魂，更谈不上个性。",
        total: 4,
        section: 3,
        chapter: 2,
      ),
      Chapter(
        "3.3 火箭飞拳与霰弹枪",
        "如果我们只有10美元来制作DOOM，那么其中的8块钱就会被拿来用于战斗系统的制作。",
        total: 4,
        section: 3,
        chapter: 3,
      ),
      Chapter(
        "开膛破肚",
        "“我们想要做的、以及你们想要玩的DOOM。”",
        total: 4,
        section: 3,
        chapter: 4,
      ),
    ],
  ),
  Section(
    "第四章：主要作品介绍",
    "DOOM的历史，探索，与重生",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "4.1 元祖系列",
        "最初的毁灭战士们",
        total: 3,
        section: 4,
        chapter: 1,
      ),
      Chapter(
        "4.2 DOOM3及其资料片",
        "因此这一次将舞台搬到了过去没有出场过的火星主基地",
        total: 3,
        section: 4,
        chapter: 2,
      ),
      Chapter(
        "4.3 重生的新DOOM",
        "它被誉为有史以来最好的第一人称动作射击游戏之一",
        total: 3,
        section: 4,
        chapter: 3,
      ),
    ],
  ),
  Section(
    "第五章：作品感受",
    "上帝花了6天创造世界，卡马克用6个游戏定义3D数码图形世界。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "5.1 DooM64：生不逢时的沧海遗珠",
        "《DooM64》神不知鬼不觉地让自己几个小时的人生就此消失。",
        total: 3,
        section: 5,
        chapter: 1,
      ),
      Chapter(
        "5.2 DOOM3：左右不逢缘",
        "它没那么爽快、流畅和激烈，但是这个游戏更加细腻沉稳。",
        total: 3,
        section: 5,
        chapter: 2,
      ),
      Chapter(
        "5.3 DOOM2016：枪炮华尔兹",
        "即便是拿着枪，也一样能找到刀光剑影间搏杀的乐趣。",
        total: 3,
        section: 5,
        chapter: 3,
      ),
    ],
  ),
  Section(
    "第六章：系列剧情解析",
    "你不太可能在这里面看到一个有太多阅读价值的故事，...这就是个典型的踢开门，杀个爽的剧本，享受那种快感",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "6.1 被地狱所恐惧的无名陆战队员",
        "下边出现了火光，你这辈子第一次见到了地狱里的世界。",
        total: 4,
        section: 6,
        chapter: 1,
      ),
      Chapter(
        "6.2 火星上的孤独幸存者",
        "邪恶总有一天会再次回归…",
        total: 4,
        section: 6,
        chapter: 2,
      ),
      Chapter(
        "6.3 传奇归来",
        "他戴上夜之哨兵的王冠，那些品尝过他利剑的人都叫他......毁灭战士",
        total: 4,
        section: 6,
        chapter: 3,
      ),
      Chapter(
        "6.4 不朽的毁灭战士",
        "他们将自己丰饶兴旺的盛世建立在他人的尸山血海之上",
        total: 4,
        section: 6,
        chapter: 4,
      ),
    ],
  ),
  Section(
    "第七章：玩家角色",
    "DOOM的主角应当是扮演他的玩家。你对他了解得越少，作为玩家本人就越有机会在游戏过程中发掘他的个性。DOOM里的陆战队员从来都没有一个官方名字，因为他就是你。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "7.1 谁是DoomGuy？",
        "严格来说，DoomGuy是处子之身。",
        total: 6,
        section: 7,
        chapter: 1,
      ),
      Chapter(
        "7.2 元祖DoomGuy和陆战队员",
        "他戴着灰白色的全罩式头盔，穿着一件绿色紧身作战服...",
        total: 6,
        section: 7,
        chapter: 2,
      ),
      Chapter(
        "7.3 Doom Slayer",
        "他是UAC在异次元勘探行动中被发现的古代人类，被一层能量包浆所保存至今。",
        total: 6,
        section: 7,
        chapter: 3,
      ),
      Chapter(
        "7.4 永恒的Doom Slayer",
        "他是神在地球上的化身，是复仇的天使，为了征讨地狱而降临人间。",
        total: 6,
        section: 7,
        chapter: 4,
      ),
      Chapter(
        "7.5 其他的主角",
        "虽然他们都是在故事中担任主角身份的存在，但基本上就不太能被称之为DoomGuy。",
        total: 6,
        section: 7,
        chapter: 5,
      ),
      Chapter(
        "7.6 不只有猛男",
        "为数不多的NPC们",
        total: 6,
        section: 7,
        chapter: 6,
      ),
    ],
  ),
  Section(
    "终章：DOOM带来的文化",
    "但DOOM早已不仅仅是属于id，也不会受缚于商业游戏市场，真正孕育并滋养它直到今天的，是那份每个人心中都或多或少会拥有自由创作与共享的精神。",
    cover: "covers/cover_1.jpg",
    chapters: [
      Chapter(
        "彩蛋、模因与文化",
        "有一些伟大成就或有趣的事件被许多人所记载传播，成为了至今都还颇具话题性的Meme。",
        total: 2,
        section: 8,
        chapter: 1,
      ),
      Chapter(
        "后记",
        "但幸运的是，这个时代能够包容许多事物。",
        total: 2,
        section: 8,
        chapter: 2,
      ),
    ],
  ),
];
